name: Continuous Delivery

on:
  push:
    branches:
      - main

    tags:
      - '**'

jobs:
  build:
    name: Build the images
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get build time
        id: build_date
        run: |
          echo "::set-output name=value::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

      - name: Build and push base
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}
            IMAGE_DESCRIPTION=${{ secrets.DOCKER_IMAGE_DESCRIPTION }}
            BUILD_DATE=${{ steps.build_date.outputs.value }}
            VCS_REF=${{ github.event.after }}
            VERSION=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
            VARIANT=base
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

      - name: Build and push with-node
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            IMAGE_NAME=${{ secrets.DOCKER_IMAGE_NAME }}
            IMAGE_DESCRIPTION=${{ secrets.DOCKER_IMAGE_DESCRIPTION }}
            BUILD_DATE=${{ steps.build_date.outputs.value }}
            VCS_REF=${{ github.event.after }}
            VERSION=${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
            VARIANT=with-node
          tags: ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}-with-node

  update-dockerhub-description:
    name: Update Docker Hub description
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Docker Hub description
        if: ${{ github.ref_name == 'main' }}
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_IMAGE_NAME }}
          short-description: ${{ github.event.repository.description }}
